### ISSUE TITLE
ImportError: cannot import name 'dyconv' from 'src.model'

### ISSUE THREAD

**Issue by kumarballapavan** [awhitewhale/MFID-Net#1]
Dear author,

I am facing the following isssue. I request you to kindly resolve the issue.

Traceback (most recent call last):
  File "src/pipeline/TrainDRADN.py", line 6, in <module>
    from src.model import dyconv
ImportError: cannot import name 'dyconv' from 'src.model'

**Comment by awhitewhale** [comment]
dyconv is part of the ablation experiments we worked on, not the optimal model, you can form src.model import DRAGN. I have made the correction on testDRADN.py. Thanks. But you need to train your dataset in trainDRADN.py first to get the checkpoint file.

**Comment by kumarballapavan** [comment]
Thanks for the guidance. I request you to kindly provide the step by step procedure to train the network i.e., arranging the datasets, setting the parameters, etc.

**Comment by awhitewhale** [comment]
You can run trainDRADN.py, but you need to modify lines 15,31 and 36-43 according to your gpu count and dataset location

**Comment by kumarballapavan** [comment]
I have made the necessary changes as you suggested, however, I am facing the following issue. Also, I request you to kindly provide the list of packages that are needed to be installed in the python environment.

Traceback (most recent call last):
  File "src/pipeline/TrainDRADN.py", line 16, in <module>
    from src.preprocess import imagepreprocess
  File "D:\Study\NIT Research\Dehazing Matlab Codes\python\2023\J MFID-Net-main\MFID-Net-main\src\pipeline/../..\src\preprocess\__init__.py", line 10, in <module>
    from torch.utils.data.decorator import \
ModuleNotFoundError: No module named 'torch.utils.data.decorator'

**Comment by awhitewhale** [comment]
Sorry for the late response, python==3.9.0, torch==1.9.0, torchvision == 0.10.0 is used. But the module torch.utils.data.decorator is not used in my code.
